### ISSUE TITLE
vdjdb.jar file missing

### ISSUE THREAD

**Issue by hl457** [antigenomics/vdjdb-standalone#11]
Hi there, 
I've built using Gradle, and it says 'BUILD SUCCESSFUL' - but when I try to run the program, I get 
"Error: Unable to access jarfile vdjdb.jar" and indeed I'm unable to find the vdjdb.jar file.

Any chance you could help?
Many thanks,
Hugo

**Comment by mikessh** [comment]
Are you running ```java -jar build/libs/vdjdb.jar``` or ```java -jar build/libs/vdjdb-1.2.5.jar```? Only the later is correct.

This is a typical error when the JAR name is misspelled
