### ISSUE TITLE
Problem of the antigen filter

### ISSUE THREAD

**Issue by Sophie1liu** [antigenomics/vdjdb-standalone#15]
Hi there,
 It can run without antigen species filter and the output file will contain all the specific CDR3 in one sample .But when i try to run java -jar -Xmx4G vdjdb-1.1.5.jar -S human -R TRB --use-fat-db --filter=``__antigen.species__ = "CMV"`` bSI2.txt CMVbSI2
  it report error that sample missing  no matter the use the pool.aa.table.txt or single sample  file.

 Is there any thing wrong of the code i write.
Thank you

manager@bl8vbox[manager] java -jar -Xmx4G vdjdb-1.1.5.jar -S human -R TRB --use-fat-db --filter=``__antigen.species__ = "CMV"`` bSI2.txt CMVbSI2
--
  | [Thu Jul 13 03:51:54 UTC 2017 Main] Loading database...
  | [Thu Jul 13 03:51:58 UTC 2017 Main] Loaded database.
  | columns: complex.id,gene,cdr3,v.segm,j.segm,species,mhc.a,mhc.b,mhc.class,antigen.epitope,antigen.gene,antigen.species,reference.id,method,meta,cdr3fix,vdjdb.score,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp, rows: 7427
  | [Thu Jul 13 03:51:58 UTC 2017 Main] Filtering using __antigen.species__.
  | [Thu Jul 13 03:54:19 UTC 2017 Main] Done.
  | columns: complex.id,gene,cdr3,v.segm,j.segm,species,mhc.a,mhc.b,mhc.class,antigen.epitope,antigen.gene,antigen.species,reference.id,method,meta,cdr3fix,vdjdb.score,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp, rows: 7427
  | [Thu Jul 13 03:54:19 UTC 2017 Main] Preparing clonotype database for homosapiens TRB.
  | [Thu Jul 13 03:54:20 UTC 2017 Main] Done.
  | columns: complex.id,gene,cdr3,v.segm,j.segm,species,mhc.a,mhc.b,mhc.class,antigen.epitope,antigen.gene,antigen.species,reference.id,method,meta,cdr3fix,vdjdb.score,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp, rows: 4427
  | [Thu Jul 13 03:54:20 UTC 2017 Main] Reading sample(s)...
  | Exception in thread "main" java.io.FileNotFoundException: Missing sample file =
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  | at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
  | at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
  | at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81)
  | at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
  | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
  | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
  | at com.antigenomics.vdjtools.sample.SampleCollection$_closure1.doCall(SampleCollection.groovy:156)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
  | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
  | at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
  | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
  | at groovy.lang.Closure.call(Closure.java:423)
  | at groovy.lang.Closure.call(Closure.java:439)
  | at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1373)
  | at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1366)
  | at org.codehaus.groovy.runtime.dgm$149.invoke(Unknown Source)
  | at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
  | at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
  | at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
  | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
  | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
  | at com.antigenomics.vdjtools.sample.SampleCollection.<init>(SampleCollection.groovy:150)
  | at com.antigenomics.vdjtools.sample.SampleCollection.<init>(SampleCollection.groovy)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  | at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
  | at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
  | at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
  | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
  | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
  | at com.antigenomics.vdjdb.Main.run(Main.groovy:194)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
  | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
  | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
  | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
  | at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:901)
  | at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:884)
  | at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:406)
  | at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
  | at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
  | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
  | at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
  | at com.antigenomics.vdjdb.Main.main(Main.groovy)

**Comment by Sophie1liu** [comment]
java -jar -Xmx4G vdjdb-1.1.5.jar -S human -R TRB --use-fat-db --filter=``__antigen.species__ = "CMV"`` bSI2.txt CMVbSI2

**Comment by mikessh** [comment]
Hello! You should use it as
```
java -jar -Xmx4G vdjdb-1.1.5.jar -S human -R TRB --use-fat-db --filter="__antigen.species__ == 'CMV'" bSI2.txt CMVbSI2
```

**Comment by Sophie1liu** [comment]
Yes, it works.
Thank you so much.
